import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./(public)/globals.css";
import { CsrfProvider } from "@/components/csrfprovider";
import { GoogleOAuthProvider } from "@react-oauth/google";

const poppins = Poppins({
  weight: ['100','200','300','400','500','600','700','800'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "TechyLads-ecommerce",
  description: "Generated by Govinda Lamsal",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
   
   <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
      <CsrfProvider>
 
          {children}
      </CsrfProvider>
    </GoogleOAuthProvider>
        
       
      
      </body>
    </html>
  );
}